# 服务端口
server:
  port: 8202

# 服务名
spring:
  application:
    name: service-cmn
  # 当前环境设置 dev开发环境 test测试环境 prod生产环境
  profiles:
    active: dev
  # MySql 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/yygh_cmn?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: yuzhijie1218
    driver-class-name: com.mysql.jdbc.Driver
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0
  # nacos服务地址
#  cloud:
#    nacos:
#      discovery:
#        server-addr: http://localhost:8848
    #设置sentinel地址
#    sentinel:
#      transport:
#        dashboard: http://127.0.0.1:8858
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/yygh_hosp
#      auto-index-creation: false
  #  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest



  #配置mapper xml文件的路径
#  mybatis-plus:
#    mapper-locations:
#      classpath: com/xxxx/yygh/mapper/xml/*.xml

#开启sentinel
#  feign:
#    sentinel:
#      enabled: true

# 控制台日志打印管理
#logging:
#  level:
#    root : debug
